version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: portfolio_website
    ports:
      - '8070:8070'
    volumes:
      - .:/var/www/html
    depends_on:
      - database
    networks:
      - laravel-net
  database:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: portfolio_website_db
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - laravel-net
volumes:
  db-data:
networks:
  laravel-net:
